---
title: "EDIF Use Case: Traffic Flow Modelling with Urban Observatory sensor data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

The EDIF project aims to identify use cases for Urban Observatory data....

### Limitations of existing traffic flow modelling

We have 

### Benefits of using UO data

ANPR cameras provide number plate

## Methods

### Data quality

Sensors with names containing the string "DUMMY" or "TEST", were excluded, as were sensors missing readings (or with readings showing zero traffic) on the majority of days within a given time period. 
For traffic data, sensors with names containing the string "BUS" were also excluded, as these appear to represent bus lanes.

The readings were incomplete during some time periods, with sensors only giving occasional readings, perhaps due to weather conditions or other factors.
If not excluded from the analysis, this would appear to suggest very low traffic counts on certain days.
Therefore, for the traffic data, we only included sensor readings from days on which at least 100 sensors recorded total traffic volumes of at least 20% of the maximum traffic volume for that sensor.
For other data, we only included sensor readings from days on which at least half of all sensors recorded a total number of readings at least 20% of the maximum number of daily readings for that sensor.

Sometimes the ANPR cameras don't send any readings for a few hours, then after that they send a single reading that contains the sum of all the vehicle plates recorded over the previous hours. 
To avoid problems related to this in time-sensitive analyses, we excluded time periods containing less than 10 readings (typically the cameras send readings every 5 minutes), and periods containing a single reading that is greater than 6 standard deviations higher than the mean reading for the given sensor.

### Wider applicability

We have created an R function to download UO datasets. 
This function can be applied to any other datasets that are stored in similar fashion.
Parameters such as dataset name, time period desired, and the base URL, can be amended as required.

## Results

We have seen that there is a relatively strong correlation between the traffic flows according to the UO sensor data and commute trips from the 2011 Census.
This is despite the ten year time gap and the fact that the census data relates solely to travel to work, while the UO sensors will pick up all trip types. 

## Traffic flow and air pollution

The PM10 values at some sensors are subject to extreme spikes, which appear to be related to particular events. 
Figure 1 shows the height of these spikes at two Newcastle sensors, alongside a more regular pattern of PM10 levels at a city centre sensor.
We are not aware of the nature of these events that caused these spikes, but they do not appear to be relevant for comparing air pollution to typical traffic flows.
Therefore we assess PM10 levels using the median value at each sensor to minimise the impact of these spikes.

We investigated whether traffic volumes could best predict PM10 particulate air pollution on the basis of area, road identity or road type. 
For the area effect, we assessed correlations between sensors within the same MSOA.
For road identity, we compared sensors on roads with the same reference (e.g. "A167").
For road type, we compared sensors on trunk, primary, secondary, and tertiary roads.
